on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        project:
          - name: Client
            path: src/Messaging.UI/Messaging.UI.csproj
          - name: Server
            path: src/Messaging.Server/Messaging.Server.csproj

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore ${{ matrix.project.name }}
        run: dotnet restore ${{ matrix.project.path }}

      - name: Build ${{ matrix.project.name }}
        run: dotnet build ${{ matrix.project.path }} --configuration Release --no-restore

      - name: Publish ${{ matrix.project.name }}
        run: |
            dotnet publish \
            ${{ matrix.project.path }} \
            -c Release \
            -o ./publish/${{ matrix.project.name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish/
          
      - name: Deploy
        if: matrix.project.name == 'Server'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "publish/Server/*"
          target: "/opt/deploy/"

     # - name: Restart Service
     #   uses: appleboy/ssh-action@v1.0.3
     #   with:
     #     host: ${{ secrets.SERVER_HOST }}
     #     username: ${{ secrets.SERVER_USER }}
     #     key: ${{ secrets.SSH_KEY }}
     #     script: |
     #       sudo systemctl restart messagingapp
